[package]
name = "myhere"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "myhere"
path = "main.rs"

[[bin]]
name = "mythere"
path = "mythere.rs"

[dependencies]
mindroid = { workspace = true, features = ["full"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { workspace = true }
