[package]
name = "mindroid-example-minimal"
version = "0.0.1"
edition = "2024"
publish = false

[[bin]]
name = "minimal"
path = "main.rs"

[dependencies]
mindroid = { workspace = true, features = ["llm-local"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
