[package]
name = "mindroid-example-persona-agent"
version = "0.0.1"
edition = "2024"
publish = false

[[bin]]
name = "persona_agent"
path = "main.rs"

[dependencies]
mindroid = { workspace = true, features = ["full"] }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
anyhow = { workspace = true }
